# Generated by Django 5.1 on 2026-06-16 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_production', models.CharField(blank=True, max_length=25, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('quantite_traitee_kg', models.FloatField(help_text='Quantité de maïs traitée (kg)')),
                ('quantite_farine_kg', models.FloatField(default=0, help_text='Farine produite (kg)')),
                ('pertes_kg', models.FloatField(default=0, help_text='Pertes (son, déchets) (kg)')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SUSPENDU', 'Suspendu'), ('TERMINE', 'Terminé')], default='EN_COURS', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='production', to='contrats.contratmouture')),
                ('meunier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Production (mouture)',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ProduitFini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sac', models.CharField(choices=[('25KG', 'Sac 25 kg'), ('50KG', 'Sac 50 kg')], max_length=5)),
                ('nombre_sacs', models.IntegerField()),
                ('poids_total_kg', models.FloatField()),
                ('reference_lot', models.CharField(blank=True, max_length=30)),
                ('date_ensachage', models.DateField(auto_now_add=True)),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_finis', to='production.production')),
            ],
            options={
                'verbose_name': 'Produit fini (sac de farine)',
                'ordering': ['-date_ensachage'],
            },
        ),
        migrations.CreateModel(
            name='StockFarine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_farine', models.CharField(default='Farine de maïs', max_length=50)),
                ('quantite_sacs', models.IntegerField(default=0)),
                ('quantite_kg', models.FloatField(default=0)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrees_stock', to='production.produitfini')),
            ],
            options={
                'verbose_name': 'Stock farine',
                'ordering': ['-date_maj'],
            },
        ),
    ]
