# Generated by Django 5.1 on 2026-06-21 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produitfini',
            name='statut_lot',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente validation'), ('VALIDE', 'Validé')], default='EN_ATTENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='BonCession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(blank=True, max_length=25, unique=True)),
                ('date_cession', models.DateField(auto_now_add=True)),
                ('nombre_sacs_25', models.IntegerField(default=0)),
                ('nombre_sacs_50', models.IntegerField(default=0)),
                ('poids_total_kg', models.FloatField(default=0)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente magasinier'), ('RECU', 'Reçu par le magasinier')], default='EN_ATTENTE', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('magasinier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_cession_recus', to=settings.AUTH_USER_MODEL)),
                ('meunier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_cession_emis', to=settings.AUTH_USER_MODEL)),
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bon_cession', to='production.production')),
            ],
            options={
                'verbose_name': 'Bon de cession produits finis',
                'ordering': ['-date_cession'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('CREATION', 'Création'), ('ANALYSE', 'Analyse laboratoire'), ('MOUTURE', 'Mouture'), ('ENSACHAGE', 'Ensachage'), ('CESSION', 'Bon de cession'), ('VALIDATION', 'Validation magasin'), ('RETRAIT', 'Retrait client')], max_length=20)),
                ('description', models.TextField()),
                ('quantite_sacs', models.IntegerField(blank=True, null=True)),
                ('quantite_kg', models.FloatField(blank=True, null=True)),
                ('date_evenement', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_lot', to=settings.AUTH_USER_MODEL)),
                ('produit_fini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='production.produitfini')),
            ],
            options={
                'verbose_name': 'Historique lot',
                'verbose_name_plural': 'Historiques lots',
                'ordering': ['date_evenement'],
            },
        ),
    ]
