# Generated by Django 5.1 on 2026-06-21 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_produitfini_statut_lot_boncession_historiquelot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquelot',
            name='date_evenement',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
