# Generated by Django 5.1 on 2026-06-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='profil_client',
            field=models.OneToOneField(blank=True, help_text='Fiche client liée (rôle Client uniquement)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compte_utilisateur', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('COMPTABLE', 'Comptable'), ('MAGASINIER', 'Magasinier'), ('LABORANTIN', 'Laborantin'), ('MEUNIER', 'Meunier'), ('CLIENT', 'Client')], max_length=20),
        ),
    ]
