# Generated by Django 5.1 on 2026-06-16 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('contrats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RESULTAT_LABO', 'Résultat laboratoire disponible'), ('LIVRAISON_PRETE', 'Farine prête à retirer'), ('RETARD', 'Retard détecté'), ('ANOMALIE', 'Anomalie')], max_length=25)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BonRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(blank=True, max_length=25, unique=True)),
                ('date_retrait', models.DateField()),
                ('quantite_sacs', models.IntegerField()),
                ('facture_reglee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_retrait', to='clients.client')),
                ('comptable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_retrait_generes', to=settings.AUTH_USER_MODEL)),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='bon_retrait', to='contrats.contratmouture')),
            ],
            options={
                'verbose_name': 'Bon de retrait',
                'ordering': ['-date_retrait'],
            },
        ),
    ]
