# Generated by Django 5.1 on 2026-06-25 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('contrats', '0003_contratmouture_type_mouture'),
        ('facturation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('COMMANDE_PRETE', 'Commande prête au retrait'), ('RETRAIT_EFFECTUE', 'Retrait effectué')], max_length=25)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clients.client')),
                ('contrat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_client', to='contrats.contratmouture')),
                ('magasinier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_client_emises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification client',
                'verbose_name_plural': 'Notifications clients',
                'ordering': ['-date_creation'],
            },
        ),
    ]
