# Generated by Django 5.1 on 2026-06-16 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('magasin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Echantillon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_echantillon', models.CharField(blank=True, max_length=25, unique=True)),
                ('date_envoi_labo', models.DateField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente — envoi à Likasi'), ('EN_COURS', "En cours d'analyse"), ('TESTE', 'Analysé')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('meunier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echantillons_envoyes', to=settings.AUTH_USER_MODEL)),
                ('reception', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='echantillon', to='magasin.reception')),
            ],
            options={
                'verbose_name': 'Échantillon',
                'ordering': ['-date_envoi_labo'],
            },
        ),
        migrations.CreateModel(
            name='ResultatLaboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_analyse', models.DateField()),
                ('taux_humidite', models.FloatField(help_text="Taux d'humidité (%)")),
                ('taux_acidite', models.FloatField(help_text="Taux d'acidité")),
                ('taux_matiere_grasse', models.FloatField(help_text='Taux de matière grasse (%)')),
                ('conforme', models.BooleanField(default=False, help_text='Maïs conforme pour mouture ?')),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('echantillon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='laboratoire.echantillon')),
                ('laborantin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultats_encodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résultat laboratoire',
                'ordering': ['-date_creation'],
            },
        ),
    ]
