# Generated by Django 5.1 on 2026-06-16 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratMouture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrat', models.CharField(blank=True, max_length=25, unique=True)),
                ('date_contrat', models.DateField(auto_now_add=True)),
                ('quantite_kg', models.FloatField(help_text='Quantité de maïs (kg)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='clients.client')),
                ('comptable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_saisis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contrat de mouture',
                'ordering': ['-date_contrat'],
            },
        ),
    ]
