# Generated by Django 5.1 on 2026-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrats', '0002_commande_contratmouture_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratmouture',
            name='type_mouture',
            field=models.CharField(choices=[('MOUTURE', 'Mouture'), ('MOUTURE_A_FACON', 'Mouture à façon')], default='MOUTURE', help_text='Type de mouture convenu avec le client', max_length=20),
        ),
    ]
