# Generated by Django 5.1 on 2026-06-16 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(blank=True, max_length=25, unique=True)),
                ('date_reception', models.DateField(auto_now_add=True)),
                ('poids_brut_kg', models.FloatField()),
                ('poids_net_kg', models.FloatField()),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reception', to='contrats.contratmouture')),
                ('magasinier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réception',
                'ordering': ['-date_reception'],
            },
        ),
        migrations.CreateModel(
            name='StockMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible_kg', models.FloatField(default=0)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('reception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='magasin.reception')),
            ],
            options={
                'verbose_name': 'Stock matière première',
                'ordering': ['-date_maj'],
            },
        ),
    ]
